---

replicaCount: 5

env:
  APP_NAME: "BACKEND APPLICATION"
  STAGE_ENVIRONMENT: "STG-ENVIRONMENT"
  REDIS_HOST: "redis-service"
  REDIS_PORT: "6379"

image:
  repository: demo-harbor.mercurybridge.org/demo-project/backend-application
  pullPolicy: IfNotPresent
  tag: release-1.0.4.0.0

rollout:
  strategy: canary
  canarySteps:
    - setWeight: 20
    - pause: {duration: 20s}
    - setWeight: 40
    - pause: {duration: 20s}
    - setWeight: 60
    - pause: {duration: 20s}
    - setWeight: 80
    - pause: {duration: 20s}

service:
  type: LoadBalancer
  port: 80

ingress:
  enabled: false
  className: "nginx"
  annotations: {}
  hosts:
    - host: stg-backend-application.local
      paths:
        - path: /
          pathType: Prefix
  tls: []

redis:
  enabled: true
  auth:
    enabled: false

resources:
  limits:
    cpu: 200m
    memory: 256Mi
  requests:
    cpu: 100m
    memory: 128Mi