apiVersion: argoproj.io/v1alpha1
kind: Rollout
metadata:
  name: {{ include "thanh-backend-chart.fullname" . }}
  labels:
    {{- include "thanh-backend-chart.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  revisionHistoryLimit: 2
  selector:
    matchLabels:
      {{- include "thanh-backend-chart.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "thanh-backend-chart.selectorLabels" . | nindent 8 }}
        version: {{ .Values.image.tag | quote }}
    spec:
      containers:
      - name: {{ .Chart.Name }}
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        ports:
        - name: http
          containerPort: {{ .Values.service.targetPort }}
          protocol: TCP
        env:
        - name: APP_NAME
          value: {{ .Values.env.APP_NAME | quote }}
        - name: STAGE_ENVIRONMENT
          value: {{ .Values.env.STAGE_ENVIRONMENT | quote }}
        - name: IMAGE_VERSION
          value: {{ .Values.env.IMAGE_VERSION | quote }}
        - name: REDIS_HOST
          value: {{ .Values.env.REDIS_HOST | quote }}
        - name: REDIS_PORT
          value: {{ .Values.env.REDIS_PORT | quote }}
        livenessProbe:
          httpGet:
            path: /
            port: http
          initialDelaySeconds: 10
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /
            port: http
          initialDelaySeconds: 5
          periodSeconds: 5
        resources:
          {{- toYaml .Values.resources | nindent 10 }}
  strategy:
    {{- if eq .Values.rollout.strategy "canary" }}
    canary:
      canaryService: {{ include "thanh-backend-chart.fullname" . }}-can
      stableService: {{ include "thanh-backend-chart.fullname" . }}-stab
      trafficRouting:
        nginx:
          stableIngress: {{ include "thanh-backend-chart.fullname" . }}
      steps:
        {{- toYaml .Values.rollout.canarySteps | nindent 8 }}
    {{- else }}
    blueGreen:
      activeService: {{ include "thanh-backend-chart.fullname" . }}-act
      previewService: {{ include "thanh-backend-chart.fullname" . }}-prev
      autoPromotionEnabled: false
    {{- end }}
